--DATABASE CREATION SECTION
USE master
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'EEDB')
DROP DATABASE EEDB
CREATE DATABASE EEDB
USE EEDB

-- TABLE CREATION SECTION

CREATE TABLE Venue (
VenueID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
VenueName VARCHAR (150) UNIQUE NOT NULL,
[Location] VARCHAR (150) NOT NULL,
Capacity INT NOT NULL ,
ImageURL VARCHAR (MAX) NOT NULL
);

CREATE TABLE Event (
EventID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
EventName VARCHAR (150) UNIQUE NOT NULL,
EventDate DATE NOT NULL,
Description VARCHAR (150) NOT NULL 
);

CREATE TABLE Booking (
BookingID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
EventID INT FOREIGN KEY REFERENCES EVENT(EventID),
VenueID  INT  FOREIGN KEY REFERENCES VENUE(VenueID),
BookingDate DATE NOT NULL
);

--TABLE ALTERATION SECTION



--TABLE INSERTION SECTION
INSERT INTO VENUE(VenueName,[Location],Capacity,ImageURL)
VALUES ('At The River','Centurion',140,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDMYpVXmM4YkWN674pmNFL9EqKzP2nkQl65g&s')

INSERT INTO EVENT(EventName,EventDate,Description)
VALUES ('MD2k24','2024-09-19','Matric dance for the matric class of 2024 from centurion secondary')

INSERT INTO BOOKING(BookingDate)
VALUES ('2024-09-19')





--TABLE MANIPULATION SECTION 
SELECT * FROM VENUE
SELECT * FROM EVENT
SELECT * FROM BOOKING


--STORED PROCEDURES SECTION






